# Generated by Django 5.0.2 on 2024-02-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelloWorld',
        ),
    ]
