# Generated by Django 5.0.2 on 2024-02-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_article_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
    ]
